### ISSUE TITLE
Cannot get resources without attributes (only with relations)

### ISSUE THREAD

**Issue by ngseer** [qvantel/jsonapi-client#25]
Client fails to process response without `"attributes"` field. Here's the trace:
```python
Traceback (most recent call last):
  File "<input>", line 10, in <module>
  File "/usr/lib64/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "<input>", line 7, in get_resource
  File "/home/seer/.local/share/virtualenvs/pbJ32E1R/lib/python3.7/site-packages/jsonapi_client/session.py", line 345, in _get_async
    return await self.fetch_document_by_url_async(url)
  File "/home/seer/.local/share/virtualenvs/pbJ32E1R/lib/python3.7/site-packages/jsonapi_client/session.py", line 466, in fetch_document_by_url_async
    await self._ext_fetch_by_url_async(url))
  File "/home/seer/.local/share/virtualenvs/pbJ32E1R/lib/python3.7/site-packages/jsonapi_client/session.py", line 474, in _ext_fetch_by_url_async
    return self.read(json_data, url)
  File "/home/seer/.local/share/virtualenvs/pbJ32E1R/lib/python3.7/site-packages/jsonapi_client/session.py", line 402, in read
    no_cache=no_cache)
  File "/home/seer/.local/share/virtualenvs/pbJ32E1R/lib/python3.7/site-packages/jsonapi_client/document.py", line 65, in __init__
    super().__init__(session, json_data)
  File "/home/seer/.local/share/virtualenvs/pbJ32E1R/lib/python3.7/site-packages/jsonapi_client/common.py", line 74, in __init__
    self._handle_data(data)
  File "/home/seer/.local/share/virtualenvs/pbJ32E1R/lib/python3.7/site-packages/jsonapi_client/document.py", line 88, in _handle_data
    self.resources.extend([ResourceObject(self.session, i) for i in data])
  File "/home/seer/.local/share/virtualenvs/pbJ32E1R/lib/python3.7/site-packages/jsonapi_client/document.py", line 88, in <listcomp>
    self.resources.extend([ResourceObject(self.session, i) for i in data])
  File "/home/seer/.local/share/virtualenvs/pbJ32E1R/lib/python3.7/site-packages/jsonapi_client/resourceobject.py", line 337, in __init__
    super().__init__(session, data)
  File "/home/seer/.local/share/virtualenvs/pbJ32E1R/lib/python3.7/site-packages/jsonapi_client/common.py", line 74, in __init__
    self._handle_data(data)
  File "/home/seer/.local/share/virtualenvs/pbJ32E1R/lib/python3.7/site-packages/jsonapi_client/resourceobject.py", line 410, in _handle_data
    self._attributes = AttributeDict(data=data['attributes'],
KeyError: 'attributes'
```
It seems that client assumes `"attributes"` field always exists in a server response JSON. But in according with [JSONAPI spec](https://jsonapi.org/format/#document-resource-objects) `"attributes"` field is optional and, depending on inplementation, may be omitted by server for resources that don't contain any attributes.

**Comment by felnne** [comment]
I have this problem as well.

**Comment by ajjn** [comment]
Fixed so closing this issue.
